"""carpi command line."""

from __future__ import annotations

import argparse
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

from carpi import __version__, bluetooth
from carpi.config import MAC, load
from carpi.probe import Probe
from carpi.transport import SocketTransport
from carpi.usb import UsbGadget
from carpi.video import encode_demo, write_ppm


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(prog="carpi")
    root.add_argument(
        "--config", type=Path, help="TOML file; default /etc/carpi/carpi.toml if present"
    )
    root.add_argument("--version", action="version", version=__version__)
    commands = root.add_subparsers(dest="command", required=True)
    probe = commands.add_parser("probe", help="connect as phone/client over Bluetooth RFCOMM")
    probe.add_argument("--target", help="vehicle Bluetooth MAC")
    probe.add_argument("--channel", type=int, help="RFCOMM channel; otherwise inspect SDP")
    probe.add_argument("-v", action="count", default=0, dest="verbose")
    commands.add_parser(
        "discover", help="list BlueZ-known devices; pair separately with bluetoothctl"
    )
    commands.add_parser("daemon", help="idle service scaffold; never initiates vehicle contact")
    picture = commands.add_parser("frame", help="write local Hello World PPM image")
    picture.add_argument("--output", type=Path, required=True)
    video = commands.add_parser("video-demo", help="encode local H.264 sample; does not stream")
    video.add_argument("--output", type=Path, required=True)
    video.add_argument("--encoder", choices=["libx264", "h264_v4l2m2m"], default="libx264")
    video.add_argument("--seconds", type=int, default=3)
    usb = commands.add_parser("usb", help="explicit development USB gadget commands")
    usb_commands = usb.add_subparsers(dest="usb_command", required=True)
    for name in ("doctor", "setup", "status", "descriptors", "teardown", "trace", "net-status"):
        usb_commands.add_parser(name)
    usb_commands.choices["setup"].add_argument(
        "--separate-power", action="store_true", help="confirm Pi is powered independently"
    )
    capture = commands.add_parser("capture", help="local, private packet capture")
    capture.add_argument("kind", choices=["usb", "network"])
    capture.add_argument("--interface", help="usbmonN or network interface; auto-select if omitted")
    capture.add_argument("--output-dir", type=Path, default=Path("captures"))
    return root


def _require_root() -> None:
    if os.geteuid() != 0:
        raise RuntimeError("run this command with sudo")


def _print_fields(fields: dict[str, str]) -> None:
    for key, value in fields.items():
        print(f"{key}: {value}")


def _usb_command(args: argparse.Namespace) -> int:
    gadget = UsbGadget()
    if args.usb_command == "doctor":
        _print_fields(gadget.doctor())
        return 0
    if args.usb_command in ("status", "descriptors"):
        _print_fields(gadget.status())
        if args.usb_command == "descriptors":
            print(
                "Actual descriptor bytes are generated by the kernel; "
                "verify on host with lsusb -v -d 1d6b:0104"
            )
        return 0
    if args.usb_command == "net-status":
        _print_fields(gadget.net_status())
        name = gadget.net_status().get("interface")
        if name and shutil.which("ip"):
            for command in (
                ["ip", "-br", "addr", "show", "dev", name],
                ["ip", "-6", "route", "show", "dev", name],
                ["ip", "-4", "route", "show", "dev", name],
            ):
                subprocess.run(command, check=False)
        return 0
    _require_root()
    if args.usb_command == "setup":
        confirmed = args.separate_power
        if not confirmed and sys.stdin.isatty():
            answer = input("Pi powered independently of the USB-C data link? Type YES: ")
            confirmed = answer == "YES"
        gadget.setup(power_confirmed=confirmed)
        _print_fields(gadget.status())
        print("[usb] W1 NCM gadget bound; inspect actual descriptors on host with lsusb -v")
    elif args.usb_command == "teardown":
        gadget.teardown()
        print("[usb] gadget unbound and removed")
    elif args.usb_command == "trace":
        gadget.trace()
    return 0


def _capture(args: argparse.Namespace) -> int:
    _require_root()
    if not shutil.which("tcpdump"):
        raise RuntimeError("tcpdump missing")
    gadget = UsbGadget()
    iface = args.interface or (
        "usbmon0" if args.kind == "usb" else gadget.net_status().get("interface")
    )
    if not iface:
        raise RuntimeError("no active NCM interface; specify --interface")
    if args.kind == "usb" and not re.fullmatch(r"usbmon[0-9]+", iface):
        raise ValueError("USB interface must be usbmonN")
    if args.kind == "network" and not re.fullmatch(r"[a-zA-Z0-9_.-]{1,15}", iface):
        raise ValueError("invalid network interface")
    if args.output_dir.is_symlink():
        raise ValueError("capture directory must not be a symlink")
    args.output_dir.mkdir(parents=True, mode=0o700, exist_ok=True)
    if args.output_dir.stat().st_mode & 0o077:
        raise RuntimeError(
            "capture directory is accessible by other users; choose a private directory"
        )
    fd, output_name = tempfile.mkstemp(
        prefix=f"carpi-{args.kind}-{time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())}-",
        suffix=".pcap",
        dir=args.output_dir,
    )
    os.close(fd)
    filename = Path(output_name)
    print(
        "Captures may include serials, MACs, credentials, location and "
        "authentication material. Keep private.",
        flush=True,
    )
    print(f"[capture] {iface} -> {filename}; Ctrl+C to stop", flush=True)
    old_umask = os.umask(0o077)
    try:
        return subprocess.call(
            [
                "tcpdump",
                "-i",
                iface,
                "-s",
                "96" if args.kind == "usb" else "256",
                "-w",
                str(filename),
            ]
        )
    finally:
        os.umask(old_umask)


def main() -> int:
    args = parser().parse_args()
    try:
        default_config = Path("/etc/carpi/carpi.toml")
        config = load(args.config or (default_config if default_config.is_file() else None))
        if args.command == "usb":
            return _usb_command(args)
        if args.command == "capture":
            return _capture(args)
        if args.command == "daemon":
            print("[carpi] idle; run probe explicitly to contact a vehicle", flush=True)
            while True:
                time.sleep(3600)
        if args.command == "discover":
            for device in bluetooth.devices():
                print(device)
            return 0
        if args.command == "frame":
            write_ppm(args.output, config.width or 640, config.height or 360)
            print(f"[video] local frame written: {args.output}")
            return 0
        if args.command == "video-demo":
            encode_demo(
                args.output,
                config.width or 640,
                config.height or 360,
                config.fps,
                args.seconds,
                args.encoder,
            )
            print(f"[video] local H.264 stream written: {args.output}")
            return 0
        target = args.target or config.bluetooth_mac
        if not MAC.fullmatch(target):
            raise ValueError("probe requires --target MAC or [vehicle].bluetooth_mac")
        if args.channel is not None and not 1 <= args.channel <= 30:
            raise ValueError("RFCOMM channel must be 1..30")
        level = logging.DEBUG if args.verbose else logging.INFO
        logging.basicConfig(level=level, format="%(message)s", stream=sys.stdout)
        channel = args.channel or bluetooth.select_channel(bluetooth.sdp_channels(target))
        logging.info("[bt] connecting to %s channel %d", target, channel)
        with bluetooth.connect(target, channel) as sock:
            state = Probe(SocketTransport(sock)).run()
        print(
            f"[auth] stopped at {state.name.lower()}; no Wi-Fi handoff or CarPlay session claimed"
        )
        return 0
    except KeyboardInterrupt:
        return 130
    except (OSError, ValueError, RuntimeError, TimeoutError, ConnectionError) as error:
        print(f"[carpi] {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
